In [1]:
import pandas as pd
import json
import requests
import os
import csv
import numpy as np

In [2]:
newCars_df= pd.read_csv(r"Vehicle.csv", encoding='cp1252')
newCars_df

C:\Users\shrey\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (56,58,193,195) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,STATE,STATENAME,ST_CASE,VEH_NO,VE_FORMS,NUMOCCS,NUMOCCSNAME,DAY,DAYNAME,MONTH,...,TRLR2VIN,TRLR2VINNAME,TRLR3VIN,TRLR3VINNAME,ADS_PRES,ADS_PRESNAME,ADS_LEV,ADS_LEVNAME,ADS_ENG,ADS_ENGNAME
0,1,Alabama,10001,1,2,2,02,7,7,2,...,777777777777,No Trailing Units,777777777777,No Trailing Units,98,Not Reported,98,Not Reported,98,Not Reported
1,1,Alabama,10001,2,2,1,01,7,7,2,...,777777777777,No Trailing Units,777777777777,No Trailing Units,98,Not Reported,98,Not Reported,98,Not Reported
2,1,Alabama,10002,1,2,1,01,23,23,1,...,777777777777,No Trailing Units,777777777777,No Trailing Units,98,Not Reported,98,Not Reported,98,Not Reported
3,1,Alabama,10002,2,2,1,01,23,23,1,...,777777777777,No Trailing Units,777777777777,No Trailing Units,98,Not Reported,98,Not Reported,98,Not Reported
4,1,Alabama,10003,1,3,2,02,22,22,1,...,777777777777,No Trailing Units,777777777777,No Trailing Units,98,Not Reported,98,Not Reported,98,Not Reported
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51242,56,Wyoming,560118,5,5,1,01,30,30,9,...,777777777777,No Trailing Units,777777777777,No Trailing Units,98,Not Reported,98,Not Reported,98,Not Reported
51243,56,Wyoming,560119,1,1,1,01,22,22,9,...,777777777777,No Trailing Units,777777777777,No Trailing Units,0,No,0,Level 0 - No Automation,0,Level 0 - No Automation
51244,56,Wyoming,560120,1,1,2,02,22,22,9,...,777777777777,No Trailing Units,777777777777,No Trailing Units,98,Not Reported,98,Not Reported,98,Not Reported
51245,56,Wyoming,560121,1,2,2,02,27,27,9,...,777777777777,No Trailing Units,777777777777,No Trailing Units,98,Not Reported,98,Not Reported,98,Not Reported
51246,56,Wyoming,560121,2,2,1,01,27,27,9,...,777777777777,No Trailing Units,777777777777,No Trailing Units,98,Not Reported,98,Not Reported,98,Not Reported

In [3]:
newCars_df = newCars_df.filter(['ST_CASE', 'VEH_NO','BODY_TYPNAME','SPEEDRELNAME','DR_SF1NAME','P_CRASH2NAME','HIT_RUNNAME'], axis=1)
newCars_df

,ST_CASE,VEH_NO,BODY_TYPNAME,SPEEDRELNAME,DR_SF1NAME,P_CRASH2NAME,HIT_RUNNAME
0,10001,1,"4-door sedan, hardtop","Yes, Exceeded Speed Limit",Reported as Unknown,Traveling in same direction with lower steady ...,No
1,10001,2,Single-unit straight truck or Cab-Chassis (GVW...,No,None,Traveling in same direction with higher speed,No
2,10002,1,"4-door sedan, hardtop","Yes, Too Fast for Conditions",None,Traveling in same direction with lower steady ...,No
3,10002,2,"Compact Utility (Utility Vehicle Categories ""S...",No,None,Traveling in same direction with higher speed,No
4,10003,1,"4-door sedan, hardtop","Yes, Exceeded Speed Limit",Driver Has a Driving Record or Driver`s Licens...,Traveling in same direction with lower steady ...,No
...,...,...,...,...,...,...,...
51242,560118,5,"Truck-tractor (Cab only, or with any number of...",No,None,From opposite direction over left lane line,No
51243,560119,1,Two Wheel Motorcycle (excluding motor scooters),"Yes, Exceeded Speed Limit",None,Off the edge of the road on the right side,No
51244,560120,1,"Compact Utility (Utility Vehicle Categories ""S...",No,None,Off the edge of the road on the left side,No
51245,560121,1,"4-door sedan, hardtop",No,Driving on Wrong Side of Two-Way Trafficway (I...,Traveling in opposite direction,No
51246,560121,2,Light Pickup,No,None,Traveling in opposite direction,No

In [4]:
newCars = newCars_df[~newCars_df.isin(['NOT APPLICABLE', 'Not Reported', 'Reported as Unknown', 'Other', 'None', 'NaN']).any(axis=1)]
newCars

,ST_CASE,VEH_NO,BODY_TYPNAME,SPEEDRELNAME,DR_SF1NAME,P_CRASH2NAME,HIT_RUNNAME
4,10003,1,"4-door sedan, hardtop","Yes, Exceeded Speed Limit",Driver Has a Driving Record or Driver`s Licens...,Traveling in same direction with lower steady ...,No
9,10006,1,"Truck-tractor (Cab only, or with any number of...",No,Improper Lane Usage,Over the lane line on left side of travel lane,No
15,10011,1,"4-door sedan, hardtop","Yes, Too Fast for Conditions",Improper Lane Usage,Off the edge of the road on the left side,No
16,10012,1,Light Pickup,No,Driver Has a Driving Record or Driver`s Licens...,Pedestrian in road,No
19,10015,1,Light Pickup,No,Improper Lane Usage,Over the lane line on left side of travel lane,No
...,...,...,...,...,...,...,...
51233,560114,1,"4-door sedan, hardtop",No,"Failure to Obey Actual Traffic Sign,Traffic Co...",Turning Left,No
51235,560115,1,Light Pickup,No,Overcorrecting,Off the edge of the road on the left side,No
51240,560118,3,"Medium/heavy Pickup (GVWR greater than 10,000 ...",No,Passing with Insufficient Distance or Inadequa...,Other vehicle stopped,No
51241,560118,4,"Truck-tractor (Cab only, or with any number of...",No,Vehicle in Road,From opposite direction over left lane line,No
51245,560121,1,"4-door sedan, hardtop",No,Driving on Wrong Side of Two-Way Trafficway (I...,Traveling in opposite direction,No

In [5]:
vehicle_df = newCars.rename(columns={"ST_CASE": "Case_Number", "VEH_NO": "Vehicle No.",
                                        "BODY_TYPNAME": "Body Type", "SPEEDRELNAME": "Speed Exceed", 
                                        "DR_SF1NAME": "Driver Safety", "P_CRASH2NAME": "Pedestrian Crash", 
                                        "HIT_RUNNAME": "Hit/Run"})
vehicle_df.head()

,Case_Number,Vehicle No.,Body Type,Speed Exceed,Driver Safety,Pedestrian Crash,Hit/Run
4,10003,1,"4-door sedan, hardtop","Yes, Exceeded Speed Limit",Driver Has a Driving Record or Driver`s Licens...,Traveling in same direction with lower steady ...,No
9,10006,1,"Truck-tractor (Cab only, or with any number of...",No,Improper Lane Usage,Over the lane line on left side of travel lane,No
15,10011,1,"4-door sedan, hardtop","Yes, Too Fast for Conditions",Improper Lane Usage,Off the edge of the road on the left side,No
16,10012,1,Light Pickup,No,Driver Has a Driving Record or Driver`s Licens...,Pedestrian in road,No
19,10015,1,Light Pickup,No,Improper Lane Usage,Over the lane line on left side of travel lane,No

In [7]:
vehicle_df.dtypes

Case_Number          int64
Vehicle No.          int64
Body Type           object
Speed Exceed        object
Driver Safety       object
Pedestrian Crash    object
Hit/Run             object
dtype: object

In [6]:
# Writing Accidents final dataframe to a csv
vehicle_df.to_csv(r"Output/vehicles_final.csv", index=False, header=True)